### ISSUE TITLE
系统设置下各应用问题清单

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-widgets#103]
### 各个菜单项存在的问题
 - [x] 各应用选项卡添加各自的权限。
 - [x] 我的资料： 配置的选项卡中“外部链接“字段值中无法为userId取活值，${global.userId} 获取不到。【配置的选项卡中“外部链接“字段值中如何取活值 #115】
     - [x] 迁移到右上角头像图标中。
 - [ ] 公司：
     - [x] 配置的选项卡中“外部链接“字段值中无法为spaceId取活值，${global.spaceId} 获取不到。【同上】
     - [ ] 记录页右上角出现“编辑”按钮（正常不会有此按钮）
     - [ ] 记录页报错，各字段无值。
 - [ ] “我的资料”和“人员”一旦选中一个，另一个也会同时选中，进入人员详细时左侧菜单选中的也不对。【人员详细界面使用amis重画 #105】
 - [ ] 人员：#129
     - [ ] 1、对象列表上缺少“新建”按钮了，出现了“删除”按钮； 
     - [ ] 2、详细页右上角缺少“编辑”、“修改密码”、“停用“、”锁定“这四个按钮。
 - [x] 部门：对象列表不是树状结构。【廖】
 - [ ] 权限集：
     - [x] 1、对象列表中“类别”字段未显示值。  【设置应用左侧菜单权限集列表上“类别”字段未显示值 #106】【廖】
     - [ ] 2、进入详细页报错：licenseOptions is not defined。【设置应用左侧权限集详细页报错：licenseOptions is not defined。 #107】【廖】
 - [ ] 简档：
      - [x] 1、对象列表中“类别”字段未显示值，【同上面权限集】
      - [ ] 2、“许可证”字段显示值异常：“data._display.license.forEach is not a function”。【廖】
      - [ ] 3、进入详细页报错：licenseOptions is not defined。【廖】
 - [ ] 应用程序：对象列表右上角缺少”新建“按钮【设置应用左侧菜单部分对象列表界面右上角缺少按钮 #111】
 - [ ] 软件包：对象列表右上角缺少“手动安装软件包”按钮【设置应用左侧菜单部分对象列表界面右上角缺少按钮 #111】
 - [ ] 对象：列表加载慢【设置应用左侧菜单对象列表加载非常慢，大概要10s #110】
 - [ ] 批准过程:  ”对象“字段显示异常：data._display.object_name.forEach is not a function
 - [ ] 字段更新: 除了“显示名称”字段，其它显示异常
 - [ ] 工作流通知: "指定对象上的用户字段"字段显示出来了
 - [ ]  流程：对象列表上缺少“新建”、“从模版新建”按钮。【设置应用左侧菜单部分对象列表界面右上角缺少按钮 #111】
 - [ ] 对象流程映射: 对象列表"对象“、”名称“、”流程“字段都没有显示出来。
 - [ ] 登录会话： 从对象列表无法进入详细页，序号上没有链接指向详细页。【没有名称字段的对象，在列表上目前没有链接可以指向记录详细界面 #112】
 - [x] 菜单选中样式问题：选中简档菜单时权限集菜单也会被选中【权限集与简档菜单合并】【廖】
 
 
### 统一的功能问题：
 - [ ] [对象列表数据量大，往下翻滚查看， 表头会悬浮在页面顶部。](https://github.com/steedos/steedos-webapp-nextjs/issues/113)
 - [ ] 选项卡滚动到左侧最底下的并点击底部菜单，滚动条会恢复到顶部了，没有保持滚动条位置 #114

### 其他问题
- [x] 所有的设置应用选项卡api名称应该统一加前缀: admin_
- [x] 选项卡分组【已确认有效果，待加上】
- [x] 应用程序启动器出现了两个设置应用，且platform界面点击后使用iframe打开了界面【已把设置应用设置为隐藏解决掉了】

**Comment by Flyingliao** [comment]
各个子任务都已处理了，可以标记done了。
